/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;


public class BookWindow extends javax.swing.JFrame {

    
    public BookWindow() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(450, 450);
        setLocation(500,200);
        setTitle("Books");
        setIconImage(new ImageIcon(getClass().getResource("/images/images.jpg")).getImage());
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/images/biblioteca.jpg"));
        JLabel fondo=new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRegister = new javax.swing.JButton();
        jComboBooks = new javax.swing.JComboBox<>();
        lblType = new javax.swing.JLabel();
        jLabelYear = new javax.swing.JLabel();
        jLabelType = new javax.swing.JLabel();
        jTextYear = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jTextTitle = new javax.swing.JTextField();
        jLabelAuthor = new javax.swing.JLabel();
        jTextAuthor = new javax.swing.JTextField();
        jLabelISBN = new javax.swing.JLabel();
        jTextISBN = new javax.swing.JTextField();
        jPanelMaterial = new javax.swing.JPanel();
        jLabelCover = new javax.swing.JLabel();
        jLabelSheets = new javax.swing.JLabel();
        jTextFieldSheets = new javax.swing.JTextField();
        jTextFieldCover = new javax.swing.JTextField();
        jPanelDigital = new javax.swing.JPanel();
        jLabelFormat = new javax.swing.JLabel();
        jLabelStorage = new javax.swing.JLabel();
        jTextFieldStorage = new javax.swing.JTextField();
        jTextFieldFormat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButtonRegister.setBackground(new java.awt.Color(51, 51, 0));
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegister);
        jButtonRegister.setBounds(290, 100, 80, 40);

        jComboBooks.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBooks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Material Book", "Digital Book" }));
        jComboBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBooksActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBooks);
        jComboBooks.setBounds(80, 20, 100, 20);
        getContentPane().add(lblType);
        lblType.setBounds(220, 20, 190, 30);

        jLabelYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelYear.setText("Year");
        getContentPane().add(jLabelYear);
        jLabelYear.setBounds(20, 200, 50, 20);

        jLabelType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelType.setText("Type");
        getContentPane().add(jLabelType);
        jLabelType.setBounds(20, 20, 50, 20);

        jTextYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextYearActionPerformed(evt);
            }
        });
        getContentPane().add(jTextYear);
        jTextYear.setBounds(80, 200, 90, 30);

        jLabelName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelName.setText("Title");
        getContentPane().add(jLabelName);
        jLabelName.setBounds(20, 60, 50, 20);

        jTextTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTitleActionPerformed(evt);
            }
        });
        getContentPane().add(jTextTitle);
        jTextTitle.setBounds(80, 60, 130, 30);

        jLabelAuthor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelAuthor.setText("Author");
        getContentPane().add(jLabelAuthor);
        jLabelAuthor.setBounds(20, 100, 50, 20);

        jTextAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAuthorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextAuthor);
        jTextAuthor.setBounds(80, 100, 130, 30);

        jLabelISBN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelISBN.setText("ISBN");
        getContentPane().add(jLabelISBN);
        jLabelISBN.setBounds(20, 150, 50, 20);

        jTextISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextISBNActionPerformed(evt);
            }
        });
        getContentPane().add(jTextISBN);
        jTextISBN.setBounds(80, 150, 130, 30);

        jLabelCover.setText("Cover");

        jLabelSheets.setText("Sheets");

        jTextFieldSheets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSheetsActionPerformed(evt);
            }
        });

        jTextFieldCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMaterialLayout = new javax.swing.GroupLayout(jPanelMaterial);
        jPanelMaterial.setLayout(jPanelMaterialLayout);
        jPanelMaterialLayout.setHorizontalGroup(
            jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaterialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMaterialLayout.createSequentialGroup()
                        .addComponent(jLabelCover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCover, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMaterialLayout.createSequentialGroup()
                        .addComponent(jLabelSheets)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSheets, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanelMaterialLayout.setVerticalGroup(
            jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMaterialLayout.createSequentialGroup()
                .addGroup(jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMaterialLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelCover))
                    .addComponent(jTextFieldCover, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelMaterialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMaterialLayout.createSequentialGroup()
                        .addComponent(jLabelSheets)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(jTextFieldSheets))
                .addContainerGap())
        );

        getContentPane().add(jPanelMaterial);
        jPanelMaterial.setBounds(200, 280, 170, 90);

        jLabelFormat.setText("Format");

        jLabelStorage.setText("Storage");

        jTextFieldStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStorageActionPerformed(evt);
            }
        });

        jTextFieldFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDigitalLayout = new javax.swing.GroupLayout(jPanelDigital);
        jPanelDigital.setLayout(jPanelDigitalLayout);
        jPanelDigitalLayout.setHorizontalGroup(
            jPanelDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDigitalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDigitalLayout.createSequentialGroup()
                        .addComponent(jLabelFormat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDigitalLayout.createSequentialGroup()
                        .addComponent(jLabelStorage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldStorage, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanelDigitalLayout.setVerticalGroup(
            jPanelDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDigitalLayout.createSequentialGroup()
                .addGroup(jPanelDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDigitalLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabelFormat))
                    .addComponent(jTextFieldFormat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDigitalLayout.createSequentialGroup()
                        .addComponent(jLabelStorage)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(jTextFieldStorage))
                .addContainerGap())
        );

        getContentPane().add(jPanelDigital);
        jPanelDigital.setBounds(20, 280, 170, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jComboBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBooksActionPerformed
        // TODO add your handling code here:
        String msj=jComboBooks.getSelectedItem().toString();
        lblType.setText(msj);
        String material="Material Book";
        if(msj.equalsIgnoreCase(material)){
            //jPanelDigital.setEnabled(false);
            jTextFieldFormat.setEnabled(false);
            jTextFieldFormat.setEditable(false);
            jTextFieldStorage.setEnabled(false);
            jTextFieldStorage.setEditable(false);
            jTextFieldCover.setEnabled(true);
            jTextFieldCover.setEditable(true);
            jTextFieldSheets.setEnabled(true);
            jTextFieldSheets.setEditable(true);
        }
        else{
            //jPanelMaterial.setEnabled(false);
            jTextFieldCover.setEnabled(false);
            jTextFieldCover.setEditable(false);
            jTextFieldSheets.setEnabled(false);
            jTextFieldSheets.setEditable(false);
            jTextFieldFormat.setEnabled(true);
            jTextFieldFormat.setEditable(true);
            jTextFieldStorage.setEnabled(true);
            jTextFieldStorage.setEditable(true);
        }
        
    }//GEN-LAST:event_jComboBooksActionPerformed

    
    private void jTextYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextYearActionPerformed
        jTextYear.setEnabled(false);
        jTextYear.setEditable(false);
    }//GEN-LAST:event_jTextYearActionPerformed

    private void jTextTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTitleActionPerformed
        jTextTitle.setEnabled(false);
        jTextTitle.setEditable(false);
    }//GEN-LAST:event_jTextTitleActionPerformed

    private void jTextAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAuthorActionPerformed
        jTextAuthor.setEnabled(false);
        jTextAuthor.setEditable(false);
    }//GEN-LAST:event_jTextAuthorActionPerformed

    private void jTextISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextISBNActionPerformed
        jTextISBN.setEnabled(false);
        jTextISBN.setEditable(false);
    }//GEN-LAST:event_jTextISBNActionPerformed

    private void jTextFieldSheetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSheetsActionPerformed
        jTextFieldSheets.setEnabled(false);
        jTextFieldSheets.setEditable(false);
    }//GEN-LAST:event_jTextFieldSheetsActionPerformed

    private void jTextFieldCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCoverActionPerformed

    private void jTextFieldStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStorageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStorageActionPerformed

    private void jTextFieldFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormatActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        
        
        
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JComboBox<String> jComboBooks;
    private javax.swing.JLabel jLabelAuthor;
    private javax.swing.JLabel jLabelCover;
    private javax.swing.JLabel jLabelFormat;
    private javax.swing.JLabel jLabelISBN;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelSheets;
    private javax.swing.JLabel jLabelStorage;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JPanel jPanelDigital;
    private javax.swing.JPanel jPanelMaterial;
    private javax.swing.JTextField jTextAuthor;
    private javax.swing.JTextField jTextFieldCover;
    private javax.swing.JTextField jTextFieldFormat;
    private javax.swing.JTextField jTextFieldSheets;
    private javax.swing.JTextField jTextFieldStorage;
    private javax.swing.JTextField jTextISBN;
    private javax.swing.JTextField jTextTitle;
    private javax.swing.JTextField jTextYear;
    private javax.swing.JLabel lblType;
    // End of variables declaration//GEN-END:variables
}
