/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import data.AvFile;
import data.LoanAv;
import domain.Audiovisuales;
import domain.Cds;
import domain.Dvds;
import domain.Laptop;
import domain.LoanCAv;
import domain.Parlantes;
import domain.Proyector;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author faubricioch
 */
public class Loan extends javax.swing.JFrame {

    /**
     * Creates new form Loan
     */
    DateFormat df= DateFormat.getDateInstance();
    public Loan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        dispositiveCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        dispField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        brandField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        goodC = new javax.swing.JRadioButton();
        badC = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        loadDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        avaY = new javax.swing.JRadioButton();
        avaN = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        regNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        returnDate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        actionCombo = new javax.swing.JComboBox();
        multa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dispositiveCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laptop", "Proyector", "Parlantes", "Cd's", "Dvd's" }));

        jLabel1.setText("Dispositivo:");

        dispField.setEditable(false);

        jLabel2.setText("Marca: ");

        brandField.setEditable(false);

        jLabel3.setText("Condición: ");

        buttonGroup1.add(goodC);
        goodC.setText("Bueno");

        buttonGroup1.add(badC);
        badC.setText("Malo");

        jLabel4.setText("Fecha de préstamo:");

        jLabel5.setText("Disponibilidad:");

        buttonGroup2.add(avaY);
        avaY.setText("Si");

        buttonGroup2.add(avaN);
        avaN.setText("No");

        jLabel6.setText("Número de registro:");

        regNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNumberActionPerformed(evt);
            }
        });

        jLabel7.setText("Fecha de devolución:");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar préstamo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        actionCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Loan", "Devolution" }));
        actionCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionComboActionPerformed(evt);
            }
        });

        multa.setText("Multa:");
        multa.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(dispField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(brandField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(goodC)
                                        .addGap(18, 18, 18)
                                        .addComponent(badC))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(loadDate, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(avaY)
                                        .addGap(18, 18, 18)
                                        .addComponent(avaN))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(returnDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(152, 152, 152)
                                        .addComponent(jButton2)))
                                .addGap(5, 5, 5)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(regNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(actionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(dispositiveCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(multa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dispositiveCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(multa))
                    .addComponent(actionCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(dispField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(brandField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(goodC)
                            .addComponent(badC))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(loadDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel7))
                    .addComponent(returnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(avaY)
                    .addComponent(avaN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regNumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(validaRN()==1 && actionCombo.getSelectedIndex()==0){
            try {
                Audiovisuales aud=new Audiovisuales();
                File file=new File("./AvFile.dat");
                AvFile avFile=new AvFile(file);
                
                aud=avFile.getAVByRegisterNumber(Integer.parseInt(regNumber.getText()),
                        dispositiveCombo.getSelectedIndex());
                if(aud==null){
                    IncompleteData inData=new IncompleteData();
                    inData.setVisible(true);
                }else{
                    dispField.setText(aud.getDispositive());
                    brandField.setText(aud.getBrand());
                    if(aud.isCondition()==true){
                        goodC.setSelected(true);
                    }else{
                        badC.setSelected(true);
                    }
                    if(aud.isAvailability()==true){
                        avaY.setSelected(true);
                    }else{
                        avaN.setSelected(true);
                    }//ifs internos
                }//if externo
                
            } catch (IOException ex) {
                Logger.getLogger(Loan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            if(actionCombo.getSelectedIndex()==1){
                try {
                    Audiovisuales aud=new Audiovisuales();
                    File file=new File("./AvFile.dat");
                    AvFile avFile=new AvFile(file);
                    
                    aud=avFile.getAVByRegisterNumber(Integer.parseInt(regNumber.getText()),
                            dispositiveCombo.getSelectedIndex());
                    if(aud==null){
                        IncompleteData inData=new IncompleteData();
                        inData.setVisible(true);
                    }else{
                        dispField.setText(aud.getDispositive());
                        brandField.setText(aud.getBrand());
                        if(aud.isCondition()==true){
                            goodC.setSelected(true);
                        }else{
                            badC.setSelected(true);
                        }
                        if(aud.isAvailability()==true){
                            avaY.setSelected(true);
                        }else{
                            avaN.setSelected(true);
                        }//ifs internos
                    }//if externo
                    
                } catch (IOException ex) {
                    Logger.getLogger(Loan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                IncompleteData inData=new IncompleteData();
                inData.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            if(validaRN()==1 && actionCombo.getSelectedIndex()==0){
                int index=dispositiveCombo.getSelectedIndex();
                File file=new File("./LoanFile.dat");
                File fileAv=new File("./AvFile.dat");
                AvFile avFile=new AvFile(fileAv);
                LoanAv avLoan=new LoanAv(file);
                LoanCAv lCav=new LoanCAv();
                
                if(index==0){
                    Laptop lap=new Laptop();
                    lap=(Laptop) avFile.getAVByRegisterNumber(Integer.parseInt(regNumber.getText()),
                            index);
                    lap.setAvailability(false);
                    avFile.setAvailability(Integer.parseInt(regNumber.getText()),
                            askAvailability(), lap, index);
                }
                if(index==1){
                    Proyector pro=new Proyector();
                    pro=(Proyector) avFile.getAVByRegisterNumber(Integer.parseInt(regNumber.getText()),
                            index);
                    pro.setAvailability(askAvailability());
                    avFile.setAvailability(Integer.parseInt(regNumber.getText()),
                            askAvailability(), pro, index);
                }
                if(index==2){
                    Parlantes par=new Parlantes();
                    par=(Parlantes) avFile.getAVByRegisterNumber(Integer.parseInt(regNumber.getText()),
                            index);
                    par.setAvailability(askAvailability());
                    avFile.setAvailability(Integer.parseInt(regNumber.getText()),
                            askAvailability(), par, index);
                }
                if(index==3){
                    Cds cds=new Cds();
                    cds=(Cds) avFile.getAVByRegisterNumber(Integer.parseInt(regNumber.getText()),
                            index);
                    cds.setAvailability(askAvailability());
                    avFile.setAvailability(Integer.parseInt(regNumber.getText()),
                            askAvailability(), cds, index);
                }
                if(index==4){
                    Dvds dvds=new Dvds();
                    dvds=(Dvds) avFile.getAVByRegisterNumber(Integer.parseInt(regNumber.getText()),
                            index);
                    dvds.setAvailability(askAvailability());
                    avFile.setAvailability(Integer.parseInt(regNumber.getText()),
                            askAvailability(), dvds, index);
                }
                
                lCav.setDispositive(dispField.getText());
                lCav.setBrand(brandField.getText());
                if(goodC.isSelected()==true){
                    lCav.setCondition(true);
                }else{
                    lCav.setCondition(false);
                }
                lCav.setLoanDate(df.format(loadDate.getDate()));
                lCav.setBackLoanDate(df.format(returnDate.getDate()));
                if(avaY.isSelected()==true){
                    lCav.setAvailability(true);
                }else{
                    lCav.setAvailability(false);
                }
                lCav.setRegisterNumber(Integer.parseInt(regNumber.getText()));
                
                avLoan.addEndRecord(lCav);
                setBlanc();
            }else{
                if(actionCombo.getSelectedIndex()==1){
                    int index=dispositiveCombo.getSelectedIndex();
                    File file=new File("./LoanFile.dat");
                    File fileAv=new File("./AvFile.dat");
                    AvFile avFile=new AvFile(fileAv);
                    LoanAv avLoan=new LoanAv(file);
                    LoanCAv lCav=new LoanCAv();

                    if(index==0){
                        Laptop lap=new Laptop();
                        lap=(Laptop) avFile.getAVByRegisterNumber(Integer.parseInt(regNumber.getText()),
                                index);
                        lap.setAvailability(false);
                        avFile.setAvailability(Integer.parseInt(regNumber.getText()),
                                askAvailability(), lap, index);
                    }
                    if(index==1){
                        Proyector pro=new Proyector();
                        pro=(Proyector) avFile.getAVByRegisterNumber(Integer.parseInt(regNumber.getText()),
                                index);
                        pro.setAvailability(askAvailability());
                        avFile.setAvailability(Integer.parseInt(regNumber.getText()),
                                askAvailability(), pro, index);
                    }
                    if(index==2){
                        Parlantes par=new Parlantes();
                        par=(Parlantes) avFile.getAVByRegisterNumber(Integer.parseInt(regNumber.getText()),
                                index);
                        par.setAvailability(askAvailability());
                        avFile.setAvailability(Integer.parseInt(regNumber.getText()),
                                askAvailability(), par, index);
                    }
                    if(index==3){
                        Cds cds=new Cds();
                        cds=(Cds) avFile.getAVByRegisterNumber(Integer.parseInt(regNumber.getText()),
                                index);
                        cds.setAvailability(askAvailability());
                        avFile.setAvailability(Integer.parseInt(regNumber.getText()),
                                askAvailability(), cds, index);
                    }
                    if(index==4){
                        Dvds dvds=new Dvds();
                        dvds=(Dvds) avFile.getAVByRegisterNumber(Integer.parseInt(regNumber.getText()),
                                index);
                        dvds.setAvailability(askAvailability());
                        avFile.setAvailability(Integer.parseInt(regNumber.getText()),
                                askAvailability(), dvds, index);
                    }
                    lCav=avLoan.getLoanByRegNumber(Integer.parseInt(regNumber.getText()));
                    if(lCav.getBackLoanDate().equals(df.format(returnDate.getDate()))){
                        multa.setText("Multa: 0");
                    }else{
                        int s1, s2, s3, s4, pay=0;
                        String date=lCav.getBackLoanDate();
                        String[]d1, d2;
                        String compare=df.format(returnDate.getDate());
                        
                        d1=date.split("/");
                        d2=compare.split("/");
                        
                        s1=Integer.parseInt(d1[0]);
                        s2=Integer.parseInt(d2[0]);
                        s3=Integer.parseInt(d1[1]);
                        s4=Integer.parseInt(d2[1]);
                        System.out.println(s1+" "+ s3+" "+s2+" "+ s4);
                        System.out.println(pay);
                        if(s3<s4){
                            for(int i=0; s3<s4; i++){
                                pay=pay+30;
                                s3++;
                            }//control meses
                        }else{
                            pay=0;
                        }
                        System.out.println(pay);
                        if(s1<s2){
                            for(int j=0; s1<s2; j++){
                                pay++;
                                s1++;
                                System.out.println(pay);
                            }//controla días
                        }else{
                            pay=pay+s2;
                        }
                        multa.setText("Multa: "+pay*100);
                    }
                    avLoan.deleteLoan(Integer.parseInt(regNumber.getText()));
                    setBlanc();
                }
            }
        }catch(IOException e){
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void actionComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionComboActionPerformed
        if(actionCombo.getSelectedIndex()==1){
            loadDate.setEnabled(false);
            multa.setVisible(true);
        }
    }//GEN-LAST:event_actionComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox actionCombo;
    private javax.swing.JRadioButton avaN;
    private javax.swing.JRadioButton avaY;
    private javax.swing.JRadioButton badC;
    private javax.swing.JTextField brandField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField dispField;
    private javax.swing.JComboBox dispositiveCombo;
    private javax.swing.JRadioButton goodC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private com.toedter.calendar.JDateChooser loadDate;
    private javax.swing.JLabel multa;
    private javax.swing.JTextField regNumber;
    private com.toedter.calendar.JDateChooser returnDate;
    // End of variables declaration//GEN-END:variables
    
    public int validaRN(){
        int prueba;
        String prove;
        try{
            prueba=Integer.parseInt(regNumber.getText());
            prove=df.format(loadDate.getDate());
            prove=df.format(returnDate.getDate());
            return 1;
        }catch(Exception e){
            return 0;
        }
    }
    
    public boolean askAvailability(){
        if(avaY.isSelected()==false){
            return false;
        }else{
            return true;
        }
    }
    
    public void setBlanc(){
        dispField.setText("");
        brandField.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
        regNumber.setText("");
        loadDate.setDate(null);
        returnDate.setDate(null);
    }
}
